### 회원가입
POST http://localhost:8080/auth/signUp
Content-Type: application/json

{
  "email": "sunlake123@naver.com",
  "password": "1234",
  "username": "아아",
  "zipcode": "01521",
  "address": "서울특별시 용산구 이촌1동 한가람아파트",
  "phone": "010-1234-5678",
  "role": "ROLE_CUSTOMER"
}
### 로그인
POST http://localhost:8080/auth/signIn
Content-Type: application/json

{
  "email": "sunlake123@naver.com",
  "password": "1234"
}

### 토큰 테스트
POST http://localhost:8080/auth/test
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzdW5sYWtlMTIzQG5hdmVyLmNvbSIsInJvbGVzIjoiUk9MRV9DVVNUT01FUiIsImlhdCI6MTY5MTE3MDc4OCwiZXhwIjoxNjkxMTc0Mzg4fQ.rT7socvpZ9-2pRZ5MfMpKCRb0UadUriXtgQ3qMwUMet0HxWM-W2DAzwrYyCpeUvuaQvqeKs7uq6BZiRq0pg_cg


{
  "email": "sunlake123@naver.com",
  "password": "1234"
}