spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  jwt:
    secret: ZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXk